### ISSUE TITLE
Unsuccessful Login

### ISSUE THREAD

**Issue by antm82** [jakajancar/DropboxUploader#61]
Hi, I'm getting an unsuccessful login suddenly? It used to work fine until a few weeks ago. I'm guessing Dropbox has changed something in its setup after issuing out the new Dropbox link with MS Office... any ideas on how to fix it? 

I am using Version bump v1.1.22 of the uploader. 

Thanks

**Comment by tooyz** [comment]
Can confirm. Getting this response:
'err:{"login_email": {"message_html": "We didn't allow this login because it appeared to be automated. Please contact \u003ca href='/support'\u003eDropbox support\u003c/a\u003e if you believe this was a mistake."}}'

**Comment by Jesus** [comment]
The devs at Dropbox must have added some additional check. I'm trying to solve the same issue for this [other ruby library](https://github.com/Jesus/dropbox-invite).

I don't have a clue yet what kind of check they've run to find out this isn't a human. I'll post it here if I find out.

**Comment by antm82** [comment]
thanks guys. Hopefully someone has the answer soon. If I work it out I'll post the info here too.

**Comment by deepu9** [comment]
Hi Guys,

I'm also having the same error "Login Unsuccessful". I'm guessing that dropbox has changed the URL structure for "HTTPS_DROPBOX_COM_LOGINACTION" or may be the URL is deprecated. I tried looking in google, but nothing came up. Does anyone where to find these urls.

## 

Thanks

**Comment by rlitten** [comment]
This is also happening to me as well. For me this stopped working on Aug 4th.

**Comment by hakre** [comment]
I also can confirm that there is an issue logging in. It's since some days. I haven't looked into this yet, just confirming the issue.

**Comment by leolamanna** [comment]
same problem (Error: Login Unsuccessful). Any ideas?? I love this script... don´t want to discard it!

**Comment by hakre** [comment]
I still could not have looked into this, so no news from my end. It's either the time of the year or it's really not easy to circumvent. But I shouldn't run any assumptions here :)

**Comment by hakre** [comment]
@deepu9 "Login Unsuccessful" should be a message from the class itself. It means that login didn't work. There is not much other reason given, it just didn't work out. I suspect a technical change on the Dropbox website.

**Comment by leolamanna** [comment]
It's just a matter of forgetting this script and try other options? Or is there any chance to the author (or third party) to fix it? what would you recommend?

**Comment by leolamanna** [comment]
=(

**Comment by hakre** [comment]
@leolamanna: Please keep commenting on topic. Always consider to add value and not just some strings of characters. It's okay to express your concerns, but just some emoticon is too few. You can see that the issue is reported and this issue is kept up-to-date as the issue progresses.

**Comment by hakre** [comment]
@leolamanna: That depends on the users perspective. Normally the time-frame of a "fix" was within a few days. If the current time is too long for your operation(s), please consider to have the other API as a backup plan until there is a fix for the issue here.

**Comment by horrorho** [comment]
I had a brief look at this, but I'm no expert so take it all with a pinch of salt.

```
POST /ajax_login HTTP/1.1
Host: www.dropbox.com
User-Agent: ...
Accept: text/plain, */*; q=0.01
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
Referer: https://www.dropbox.com/login
Content-Length: ...
Cookie: locale=en; gvc=...; cookie_notif=seen; t=...; js_csrf=...
DNT: 1
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
is_xhr=true&t=...&cont=/&require_role=&refresh_token=&email_sig=&signup_data=&third_party_auth_experiment=CONTROL&signup_tag=&login_email=...&login_password=...&remember_me=True&login_sd=...
```

Part of the  issue _appears_ to surround the post data item login_sd (rightmost bottom line), which corresponds to cyfd-vfl0o0UyQ.js. There's a fair bit of voodoo including the capture of browser details and user events. It's not trivial and it's not immediately obvious to me what the offending sub-field/s might be.

I **can** get automated logins to work via PhantomJS. If this interests you I'd be more than happy to share the details.

Unless there's a header/ post field combination that bypasses the automation check, the js function needs to be analysed and a acceptable spoofer of login_sd created. Failing that a PhantomJS  assisted login with cookie capturing _may_ work.

Sadly the more important question is how long can you keep the cat and mouse game going with the Dropbox developers. It's clear they do not want automated scripts.

**Comment by dmccall** [comment]
I am having the same problems with unsuccessful login, and it is disabling a part of my business. Hopefully someone can find a solution quickly.

**Comment by leolamanna** [comment]
@hakre: ok my teacher

**Comment by rlitten** [comment]
Looks like Dropbox knows this script and says to use the dropbox APIs
https://www.dropboxforum.com/hc/en-us/community/posts/204558145-Why-did-Dropbox-stop-allowing-file-uploads-using-the-API-

**Comment by rlitten** [comment]
I pulled down the core apis from Dropbox and created an app. And have this working for me. If anyone is interested, I will try to post my code later.

**Comment by lideshi** [comment]
The login post fields for dropbox has increased and it's looking for a lot
more fields.  Just pass those new fields in.

**Comment by joostdb** [comment]
It seems that the script works again. This morning I was able to download files tot my dropbox account.

**Comment by leolamanna** [comment]
@joostdb: not at all in my case... still NOT working: "Error: Login Unsuccessful"

@lideshi: can you tell me, which are the required fields to pass... how to do that?
Thanks for your help.

**Comment by lideshi** [comment]
It's pretty nasty.  You can see it using Chrome dev tool >Network

**Comment by leolamanna** [comment]
sorry... I try to find the way, but it seems that I'm so noob to solve it by my self  =(
checked and rechecked: the script is still NOT working

**Comment by neovea** [comment]
Hello, I'm adding myself as unsuccesfully login in via this script. But I developped a Symfony2 controller mounths ago. I'll try to check if it still works (it uses core api) and adapt it if so.

**Comment by hakre** [comment]
Seems like it worked for two days but stopped again. From the forum thread Dropbox communicates that "automated logins" are not wanted. This PHP library needs a HTTP based REST API that allow authentication across as little as two HTTP requests with cookie usage (HTTP STATE MANAGEMENT MECHANISM). Looks like that Dropbox is not willing any longer (for no reason given) to provide that. Also no reason has been provided what the issue with automated logins is.

Next to that, it seems that Dropbox is not willing to provide a PHP 5.2 compatible PHP API.

**Comment by neovea** [comment]
That means using the API ouside a browser is excluded as Dropbox asks for cookie usage, isn't it ? I think about executing this script via a cron job. Otherwise adapting the script to get a RESTfull class could be an option.

**Comment by leolamanna** [comment]
@rlitten: could you share your script?? Even when I was trying to avoid making any changes in my website, it seems that the autor of this script can´t (or is not interested on to) fix the problem and I'm really needing to find a solution... or (under the circumstances) try an alternative.
Thanks in advance!

**Comment by rlitten** [comment]
@leolamanna give this a shot: https://github.com/rlitten/MysqldumpDropbox
Let me know if it needs any tweaks, but it should work if you follow the steps.

**Comment by cballenar** [comment]
Thanks @rlitten that was very helpful!

**Comment by leolamanna** [comment]
@rlitten, sorry for the delay on my feedback... but I was really unabled to take the time to see it sooner.
I follow all your instructions carefully but I have no way to get exec permissions at the server... so It's not possible for me to run MysqlToDropbox.php as required.
Is there any way to avoid this requirement?

**Comment by rlitten** [comment]
You have access to place the MysqlToDropbox.php script to your site but not change the permissions?

**Comment by leolamanna** [comment]
Many thanks for your quick response! I'm able to change the file premissions... but I get this message when I run the MysqlToDropbox.php:
Warning: exec() has been disabled for security reasons in /home/u298870474/public_html/MysqlToDropbox.php on line 28
File up_2015_09_12.tgz does not exist

**Comment by rlitten** [comment]
Ok the exec command you would have used with this script originally, so that's why I don't understand why your not able to run this now. So your hosting company has exec disabled.

**Comment by leolamanna** [comment]
I have setted 777 file permissions for the MysqlToDropbox.php file... and this is all I've made.- Then, while trying to run de php, I get this error message.
I'm a total rookie... I don´t know if I'm missing something!

**Comment by leolamanna** [comment]
BTW, I have checked the file permissions for the original PHP file (DropboxUploader.php) and it's not 777 but 644... so it has no ecex

**Comment by leolamanna** [comment]
I have solved by the solution given at
http://www.easiscripts.com/upload-files-on-dropbox-without-curl-using-php/

the bad news; there is no  password protection for the upload form, so anyone can upload freely to your dropbox account  (I will try to protect the form instead)
the good news: it works!! just by adding "app key" and "app secret" (no access token needed)

on the other hand, I need to find the way to customize A LOT of things... since it's has a REALLY BASIC behaivor

**Comment by grenzor** [comment]
Where is the developer? Issue is still ongoing with no solution :/

**Comment by Yhazius** [comment]
Sorry @leolamanna, I'm using that system but I can not change the default folder (application) for the public folder. You know how I can do this?

**Comment by leolamanna** [comment]
@Yhazius, as far as I know, the storage folder depends exclusively on the Dropbox App and as I understand the process, there should be not possible to change it by the form itself.
if there is a way to do it, should be from the application settings (Dropbox) and as far as I could see, is not an option ... but maybe someone here knows a way and can give more accurate information than I can provide!
Sorry to be not so helpful... but I'm a total noob on this!! jejejejeee

**Comment by Yhazius** [comment]
@leolamanna a lot of thanks! don't worry, i will continue testing... xD

**Comment by hakre** [comment]
@neovea: Sorry for the late reply, no cookie-usage is not the problem. This Dropbox Uploader class can deal with cookie usage. It's more the handle the login properly.

**Comment by stevenwoods** [comment]
Unfortunately I don't think this will work anymore. I've put together a script that will show you how to upload a file. I've taken a look at the examples files and put this together.
https://gist.github.com/stevenwoods/6131e92ac4d5958017a5
